import { StyleSheet } from 'react-native';
import { typography } from '../../constants/theme';

export const datingColors = {
  pink: '#F50057',
  pinkLight: '#FFF2F6',
  dark: '#3A0718',
  white: '#FFFFFF',
  muted: '#8A8A8A',
  border: '#C8C8C8',
  lightBorder: '#E6E6E6',
};

export const datingCommonStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: datingColors.white,
  },
  header: {
    height: 56,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 26,
    ...typography.Inter[700],
    color: datingColors.dark,
    marginLeft: 12,
  },
  label: {
    fontSize: 13,
    lineHeight: 17,
    ...typography.Inter[600],
    color: datingColors.dark,
    marginBottom: 6,
  },
  input: {
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: datingColors.border,
    paddingHorizontal: 14,
    fontSize: 14,
    color: datingColors.dark,
    backgroundColor: datingColors.white,
    marginBottom: 12,
  },
  textarea: {
    minHeight: 96,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: datingColors.border,
    paddingHorizontal: 14,
    paddingTop: 12,
    fontSize: 14,
    lineHeight: 19,
    color: datingColors.dark,
    textAlignVertical: 'top',
    marginBottom: 4,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: datingColors.white,
    paddingHorizontal: 16,
    paddingTop: 10,
    flexDirection: 'row',
    gap: 8,
  },
  primaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: datingColors.pink,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: datingColors.white,
    fontSize: 16,
    ...typography.Inter[700],
  },
  outlineButton: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: datingColors.pink,
    backgroundColor: datingColors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineButtonText: {
    color: datingColors.pink,
    fontSize: 16,
    ...typography.Inter[700],
  },
  tag: {
    minHeight: 34,
    borderRadius: 17,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: datingColors.white,
    borderWidth: 1,
    borderColor: datingColors.border,
    marginRight: 8,
    marginBottom: 8,
  },
  tagActive: {
    backgroundColor: datingColors.pink,
    borderColor: datingColors.pink,
  },
  tagText: {
    fontSize: 14,
    color: datingColors.dark,
  },
  tagTextActive: {
    color: datingColors.white,
    ...typography.Inter[600],
  },
  hint: {
    marginTop: 4,
    marginBottom: 12,
    fontSize: 12,
    color: '#B0B0B0',
  },
  sectionTitle: {
    fontSize: 24,
    lineHeight: 30,
    ...typography.Inter[700],
    color: datingColors.dark,
  },
});
